apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "isolated-development-space-data-{{ .Values.name }}-claim"
  labels:
    app.kubernetes.io/name: "isolated-development-space-data-{{ .Values.name }}"
    app.kubernetes.io/component: "data"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-storage-data-{{ .Values.name }}"
  resources:
    requests:
      storage: 10Gi
