apiVersion: v1
kind: ServiceAccount
metadata:
  name: "isolated-development-space-service-{{ .Values.name }}"
  labels:
    app.kubernetes.io/name: "isolated-development-space"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/component: "serviceaccount"
