apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "isolated-development-space-certs-{{ .Values.name }}-claim"
  labels:
    app.kubernetes.io/name: "isolated-development-space-certs-{{ .Values.name }}"
    app.kubernetes.io/component: "certs"
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: "local-storage-certs-{{ .Values.name }}"
  resources:
    requests:
      storage: "{{ .Values.storage.certs }}"
