apiVersion: v1
kind: PersistentVolume
metadata:
  name: "isolated-development-space-certs-{{ .Values.name }}"
  labels:
    app.kubernetes.io/name: "isolated-development-space-certs-{{ .Values.name }}"
    app.kubernetes.io/component: "certs"
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage-certs-{{ .Values.name }}"
  local:
    path: "{{ .Values.dataDirectories.certs }}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ .Values.targetHostname }}"
