apiVersion: apps/v1
kind: Deployment
metadata:
  name: "isolated-development-space-deployment-{{ .Values.name }}"
  labels:
    app.kubernetes.io/name: "isolated-development-space-deployment-{{ .Values.name }}"
    user: "{{ .Values.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "isolated-development-space-deployment-{{ .Values.name }}"
      user: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "isolated-development-space-deployment-{{ .Values.name }}"
        user: "{{ .Values.name }}"
    spec:
      serviceAccountName: "isolated-development-space-service-{{ .Values.name }}"
      containers:
        - name: vscode-tunnel
          image: "ghcr.io/harp-research-inc/vscode-cli-tunnel-docker:{{ .Chart.AppVersion }}-full-dev"
          imagePullPolicy: IfNotPresent

          env:
            - name: VSCODE_CLI_DATA_DIR
              value: "/vscode/.tunnel"
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: DOCKER_CERT_PATH
              value: "/clientCerts"
            - name: DOCKER_HOST
              value: "tcp://localhost:2376"
          volumeMounts:
            - name: data
              mountPath: "/vscode"
            - name: certs
              mountPath: "/clientCerts"
              subPath: "client"

        - name: dind
          image: "docker:27.3.1-dind"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "docker info"
            initialDelaySeconds: 15
          env:
            - name: DOCKER_TLS_CERTDIR
              value: "/certs"
          volumeMounts:
            - name: data
              mountPath: "/vscode"
            - name: certs
              mountPath: "/certs"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "isolated-development-space-data-{{ .Values.name }}-claim"
        - name: certs
          persistentVolumeClaim:
            claimName: "isolated-development-space-certs-{{ .Values.name }}-claim"
