apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "isolated-development-space-docker-data-{{ .Values.name }}-claim"
  labels:
    app.kubernetes.io/name: "isolated-development-space-docker-data-{{ .Values.name }}"
    app.kubernetes.io/component: "data"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-storage-docker-data-{{ .Values.name }}"
  resources:
    requests:
      storage: "{{ .Values.storage.dockerData }}"
