name: "Lint helm chart"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install helm
        uses: azure/setup-helm@v4.2.0
      - name: Lint helm chart
        run: helm lint charts/isolated-development-space -f .github/test-values.yaml
